import {createClient} from '@supabase/supabase-js';
import {api,escapeHTML as esc,money,safeImage} from './api.js';
const $=s=>document.querySelector(s),form=$('#product-form'),editor=$('#editor');
let client,categories=[],page=1,query='',epoch=0,timer;
const config={url:import.meta.env.VITE_SUPABASE_URL,key:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY};
const message=(text,error=false)=>{$('#admin-message').textContent=text;$('#admin-message').classList.toggle('error',error);};
async function token(){const {data}=await client.auth.getSession();if(!data.session)throw new Error('Inicia sesión de nuevo.');return data.session.access_token;}
async function admin(path,options={}){try{return await api('/admin'+path,{...options,token:await token()});}catch(e){if([401,403].includes(e.status)){lock();message(e.message,true);}throw e;}}
function lock(){epoch++;editor.close();form.reset();$('#dashboard').hidden=true;$('#login-section').hidden=false;$('#admin-products').replaceChildren();}
async function loadCategories(){categories=(await admin('/categories')).categories;$('#categories-list').innerHTML=categories.map(c=>`<div class="category-row"><span><strong>${esc(c.name)}</strong> · ${c.active?'Visible':'Oculta'}</span><button class="button subtle" data-category="${esc(c.id)}">Editar</button></div>`).join('');$('#categories-list').querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{const c=categories.find(x=>x.id===b.dataset.category),f=$('#category-form');for(const key of ['id','name','slug','sort_order'])f.elements[key].value=c[key];f.elements.active.checked=c.active;f.elements.name.focus();});}
async function loadProducts(){const current=++epoch;$('#admin-products').textContent='Cargando perfumes…';try{const data=await admin('/products?'+new URLSearchParams({page,q:query}));if(current!==epoch)return;$('#admin-count').textContent=data.total+' perfumes';$('#admin-page-number').textContent='Página '+page;$('#admin-prev').disabled=page===1;$('#admin-next').disabled=page*30>=data.total;$('#admin-products').innerHTML=data.products.length?data.products.map(p=>`<article class="admin-product">${safeImage(p.images[0])?`<img src="${esc(p.images[0])}" alt="" loading="lazy">`:'<span class="admin-photo-placeholder">Sin foto</span>'}<div><h3>${esc(p.name)}</h3><p>${esc(p.brand)} · ${esc(p.category_name)}</p><span>${p.active?'Publicado':'Borrador'}${p.featured?' · Destacado':''}</span><p>${p.variants.filter(v=>v.active).map(v=>`${esc(v.label)}: ${money(v.price_cents)} · ${v.stock} uds.`).join('<br>')}</p></div><button class="button subtle" data-edit="${esc(p.id)}">Editar</button></article>`).join(''):'<p class="empty-admin">Aún no hay perfumes. Añade el primero para comenzar.</p>';$('#admin-products').querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{try{openEditor((await admin('/products/'+b.dataset.edit)).product);}catch(e){message(e.message,true);}});}catch(e){if(current===epoch)$('#admin-products').textContent=e.message;}}
async function unlock(){try{await admin('/me');await loadCategories();$('#login-section').hidden=true;$('#dashboard').hidden=false;message('');await loadProducts();}catch(e){lock();message(e.message,true);}}
function variantRow(v={label:'',volume_ml:null,price_cents:0,stock:0,active:true}){const row=document.createElement('div');row.className='variant-row';row.dataset.id=v.id||'';row.innerHTML=`<label>Presentación<input data-field="label" value="${esc(v.label)}" required maxlength="80" placeholder="100 ml"></label><label>Mililitros<input data-field="volume_ml" type="number" min="1" max="10000" value="${v.volume_ml??''}"></label><label>Precio RD$<input data-field="price" type="number" min="0.01" max="1000000" step="0.01" value="${v.price_cents?v.price_cents/100:''}" required></label><label>Existencias<input data-field="stock" type="number" min="0" max="1000000" value="${v.stock}" required></label><label class="checkbox"><input data-field="active" type="checkbox" ${v.active?'checked':''}>Activa</label>${v.id?'':'<button type="button" class="remove-variant" aria-label="Quitar presentación nueva">×</button>'}`;row.querySelector('.remove-variant')?.addEventListener('click',()=>row.remove());$('#variant-rows').append(row);}
function openEditor(p){form.reset();$('#editor-error').textContent='';$('#editor-title').textContent=p?'Editar perfume':'Nuevo perfume';form.elements.category_id.innerHTML=categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}${c.active?'':' (oculta)'}</option>`).join('');$('#variant-rows').replaceChildren();if(p){for(const key of ['id','version','name','slug','brand','description','category_id','family','concentration','notes'])form.elements[key].value=p[key]??'';form.elements.active.checked=p.active;form.elements.featured.checked=p.featured;form.elements.images.value=p.images.join('\n');p.variants.forEach(variantRow);}else{form.elements.id.value='';form.elements.version.value='';variantRow();}editor.showModal();}
function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('Introduce precios positivos con hasta dos decimales.');const [a,b='']=value.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));}
form.addEventListener('submit',async e=>{e.preventDefault();$('#editor-error').textContent='';const save=$('#save-product');save.disabled=true;try{const f=form.elements,p={};for(const key of ['name','slug','brand','description','category_id','family','concentration','notes'])p[key]=f[key].value.trim();p.active=f.active.checked;p.featured=f.featured.checked;p.images=f.images.value.split('\n').map(v=>v.trim()).filter(Boolean);p.variants=[...document.querySelectorAll('.variant-row')].map(row=>{const get=k=>row.querySelector(`[data-field="${k}"]`);return{...(row.dataset.id?{id:row.dataset.id}:{}),label:get('label').value.trim(),volume_ml:get('volume_ml').value?Number(get('volume_ml').value):null,price_cents:cents(get('price').value),stock:Number(get('stock').value),active:get('active').checked};});const id=f.id.value;if(id)p.version=Number(f.version.value);await admin('/products'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(p)});editor.close();message('Perfume guardado.');await loadProducts();}catch(e){$('#editor-error').textContent=e.message;}finally{save.disabled=false;}});
form.elements.name.addEventListener('input',()=>{if(!form.elements.id.value)form.elements.slug.value=form.elements.name.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');});
$('#add-variant').onclick=()=>variantRow();$('#close-editor').onclick=$('#cancel-editor').onclick=()=>editor.close();$('#new-product').onclick=()=>openEditor();
$('#admin-prev').onclick=()=>{page--;loadProducts();};$('#admin-next').onclick=()=>{page++;loadProducts();};$('#admin-search').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{query=e.target.value;page=1;loadProducts();},300);};
for(const type of ['products','categories'])$('#tab-'+type).onclick=()=>{for(const name of ['products','categories']){$('#'+name+'-section').hidden=name!==type;$('#tab-'+name).setAttribute('aria-pressed',String(name===type));}};
$('#reset-category').onclick=()=>{$('#category-form').reset();$('#category-form').elements.id.value='';};
$('#category-form').onsubmit=async e=>{e.preventDefault();const f=e.target.elements,b=e.submitter;b.disabled=true;try{const id=f.id.value;await admin('/categories'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify({name:f.name.value.trim(),slug:f.slug.value.trim(),sort_order:Number(f.sort_order.value),active:f.active.checked})});await loadCategories();e.target.reset();f.id.value='';message('Categoría guardada.');}catch(error){message(error.message,true);}finally{b.disabled=false;}};
$('#login-form').onsubmit=async e=>{e.preventDefault();if(!client)return;const b=e.submitter;b.disabled=true;message('Comprobando acceso…');try{const {error}=await client.auth.signInWithPassword({email:e.target.elements.email.value.trim(),password:e.target.elements.password.value});if(error)throw new Error('No pudimos iniciar sesión. Revisa el correo y la contraseña.');e.target.elements.password.value='';await unlock();}catch(error){message(error.message,true);}finally{b.disabled=false;}};
$('#logout').onclick=async()=>{lock();try{await client.auth.signOut();message('Sesión cerrada.');}catch{message('Sesión local cerrada.',true);}};
if(config.url&&config.key){try{client=createClient(config.url,config.key,{auth:{storage:sessionStorage,persistSession:true}});client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')lock();});const {data}=await client.auth.getSession();if(data.session)await unlock();}catch{message('Revisa la configuración de Supabase.',true);}}
else{message('Falta configurar Supabase. Sigue la guía docs/SUPABASE-PASO-A-PASO.md del proyecto.',true);$('#login-form').querySelector('button').disabled=true;}
